### ISSUE TITLE
[ads] Optimize database queries

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#20931]
Need to look through Brave Ads SQL statements and find not optimal ones, like this [statement](https://github.com/brave/brave-core/blob/master/vendor/bat-native-ads/src/bat/ads/internal/database/tables/ad_events_database_table.cc#L149)

Also update getters to only return what is needed, as some getters return all rows

**Comment by btlechowski** [comment]
Verified with

Brave | 1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit)
-- | --
Revision | 5d9143e1a0812c53bdc27fd5384591254306a88c
OS | Linux



#### Notification ads - default_ads_per_hour

<details>

```
[4163:4163:0403/170736.777012:VERBOSE2:permission_rules.cc(229)] Notification ad cannot be shown as minimum wait time has not passed
[4163:4163:0403/170736.777281:VERBOSE1:notification_ad_serving.cc(77)] Notification ad not served: Not allowed due to permission rules

```

after browser restart:
```
[4556:4556:0403/170854.681654:VERBOSE2:permission_rules.cc(229)] Notification ad cannot be shown as minimum wait time has not passed
[4556:4556:0403/170854.681892:VERBOSE1:notification_ad_serving.cc(77)] Notification ad not served: Not allowed due to permission rules

```

verified capping is released:
```
[4886:4886:0403/172305.986978:VERBOSE1:notification_ad_handler.cc(184)] Served notification ad:
  placementId: dd0aba4c-59b5-4814-9435-70bba029c566
  creativeInstanceId: 94464eab-dae5-4e4e-9d93-d5b2d0aeb724
  creativeSetId: 586d9c8f-9573-4eac-8d66-c002615f7514
  campaignId: d1e25388-b362-4f30-bd4b-36b8205e59e5
  advertiserId: a34de75d-5654-4331-8713-8f4d4e2b6bf7
  segment: untargeted
  title: Vivamus sagittis lacus vel aug
  body: Duis mollis, est non commodo luctus, nisi erat porttitor lig
  targetUrl: https://www.apple.com/
[4886:4886:0403/172306.000075:VERBOSE6:ads_service_impl.cc(849)] Timeout notification ad with placement id dd0aba4c-59b5-4814-9435-70bba029c566 in 120 s
[4886:4886:0403/172306.016462:VERBOSE3:notification_ad_handler.cc(195)] Served notification ad with placement id dd0aba4c-59b5-4814-9435-70bba029c566 and creative instance id 94464eab-dae5-4e4e-9d93-d5b2d0aeb724

```

</details>


#### Notification ads - maximum_ads_per_day

<details>

```
[5217:5217:0403/171440.935689:VERBOSE2:permission_rules.cc(209)] You have exceeded the allowed notification ads per day
[5217:5217:0403/171440.936042:VERBOSE1:notification_ad_serving.cc(77)] Notification ad not served: Not allowed due to permission rules

```

after browser restart:
```
[5595:5595:0403/171531.229872:VERBOSE2:permission_rules.cc(209)] You have exceeded the allowed notification ads per day
[5595:5595:0403/171531.230093:VERBOSE1:notification_ad_serving.cc(77)] Notification ad not served: Not allowed due to permission rules

```

released:
```
[6056:6056:0404/171627.841092:VERBOSE1:notification_ad_handler.cc(184)] Served notification ad:
  placementId: 9ed053e5-4943-4829-9d76-c5fb3d2c24fe
  creativeInstanceId: 94464eab-dae5-4e4e-9d93-d5b2d0aeb724
  creativeSetId: 586d9c8f-9573-4eac-8d66-c002615f7514
  campaignId: d1e25388-b362-4f30-bd4b-36b8205e59e5
  advertiserId: a34de75d-5654-4331-8713-8f4d4e2b6bf7
  segment: untargeted
  title: Vivamus sagittis lacus vel aug
  body: Duis mollis, est non commodo luctus, nisi erat porttitor lig
  targetUrl: https://www.apple.com/

```

</details>


#### ntpsi - maximum_ads_per_hour

<details>

```
[22835:22835:0403/185342.755641:VERBOSE2:permission_rules.cc(181)] You have exceeded the allowed new tab page ads per hour
[22835:22835:0403/185342.756916:VERBOSE1:new_tab_page_ad_serving.cc(43)] New tab page ad not served: Not allowed due to permission rules

```


released:
```
[23120:23120:0403/195425.198013:VERBOSE1:new_tab_page_ad_handler.cc(169)] Served new tab page ad:
  placementId: 23828ab3-643c-44b7-aa8d-4d2facce9f2c
  creativeInstanceId: 0aaafcc8-2c2c-45e1-bf89-9244d3c331d0
  creativeSetId: b03f540a-d70a-432c-af2d-10702fa6cc7e
  campaignId: 10477b6c-eac9-4ef3-8f3b-caf4e8e83e07
  advertiserId: 803953a8-56b4-4d4b-942a-fa81357f1427
  segment: untargeted
  companyName: BMW
  imageUrl: https://mobile-data-dev.s3.brave.software/assets/ntp-si/69aa9044-d6d2-4e24-ac03-958391b2bb7a.png
  alt: BMW
  targetUrl: https://www.bmwusa.com/?brave-creative-id=0aaafcc8-2c2c-45e1-bf89-9244d3c331d0&source=image1
  wallpaper:
    imageUrl: https://mobile-data-dev.s3.brave.software/assets/ntp-si/72ba7af0-160e-4b1b-bdec-5ae0d166f7e1.jpg
    focalPoint:
      x: 756
      y: 720

```

</details>


#### ntpsi - maximum_ads_per_day

<details>

```
[23819:23819:0403/195739.443535:VERBOSE2:permission_rules.cc(157)] You have exceeded the allowed new tab page ads per day
[23819:23819:0403/195739.444074:VERBOSE1:new_tab_page_ad_serving.cc(43)] New tab page ad not served: Not allowed due to permission rules

```


released:
```
[24079:24079:0404/195813.329750:VERBOSE1:new_tab_page_ad_handler.cc(169)] Served new tab page ad:
  placementId: 22854a71-6638-455c-b4bb-f00882691b8a
  creativeInstanceId: 0aaafcc8-2c2c-45e1-bf89-9244d3c331d0
  creativeSetId: b03f540a-d70a-432c-af2d-10702fa6cc7e
  campaignId: 10477b6c-eac9-4ef3-8f3b-caf4e8e83e07
  advertiserId: 803953a8-56b4-4d4b-942a-fa81357f1427
  segment: untargeted
  companyName: BMW
  imageUrl: https://mobile-data-dev.s3.brave.software/assets/ntp-si/69aa9044-d6d2-4e24-ac03-958391b2bb7a.png
  alt: BMW
  targetUrl: https://www.bmwusa.com/?brave-creative-id=0aaafcc8-2c2c-45e1-bf89-9244d3c331d0&source=image1
  wallpaper:
    imageUrl: https://mobile-data-dev.s3.brave.software/assets/ntp-si/72ba7af0-160e-4b1b-bdec-5ae0d166f7e1.jpg
    focalPoint:
      x: 756
      y: 720

```

</details>


#### Brave news inline ads - maximum_ads_per_hour

<details>

```
[24728:24728:0403/190220.864884:VERBOSE2:permission_rules.cc(327)] You have exceeded the allowed inline content ads per hour
[24728:24728:0403/190220.868464:VERBOSE1:inline_content_ad_serving.cc(48)] Inline content ad not served: Not allowed due to permission rules

```


released:
```
[25064:25064:0403/200416.412171:VERBOSE1:inline_content_ad_handler.cc(183)] Served inline content ad:
  placementId: 4c5679ca-ee62-486a-b2d0-745628cf0ac6
  creativeInstanceId: e4958d00-e35c-4134-a408-1fbcf274d5ae
  creativeSetId: 8b848823-c47f-43de-a753-2efa8dea6863
  campaignId: 07de7f05-ab32-4af0-a350-a1bce4427eac
  advertiserId: 93130af3-2def-4ecb-b836-b3772e73b3c9
  segment: untargeted
  title: Staging - Inline Test 1
  description: Fung Brave News Inline Display Ad - mac/linux
  imageUrl: https://pcdn.brave.com/brave-ads/468beb93-2458-5d3e-8d7b-bc1f387d2e9b.webp.pad
  dimensions: 900x750
  ctaText: Work at Brave
  targetUrl: https://brave.com/careers

```

</details>

#### Brave news inline ads - maximum_ads_per_day

<details>

```
[26038:26038:0403/201135.236203:VERBOSE2:permission_rules.cc(316)] You have exceeded the allowed inline content ads per day
[26038:26038:0403/201135.236850:VERBOSE1:inline_content_ad_serving.cc(48)] Inline content ad not served: Not allowed due to permission rules

```


released:
```
[26298:26298:0404/201210.894193:VERBOSE1:inline_content_ad_handler.cc(183)] Served inline content ad:
  placementId: 758bef1a-3395-4518-89db-dd1544992ca1
  creativeInstanceId: 211a9ff9-48bf-4b79-bd2a-f6b450edac0a
  creativeSetId: 8b848823-c47f-43de-a753-2efa8dea6863
  campaignId: 07de7f05-ab32-4af0-a350-a1bce4427eac
  advertiserId: 93130af3-2def-4ecb-b836-b3772e73b3c9
  segment: untargeted
  title: [Staging] Aspect Ratio
  description: Test Aspect Ratio
  imageUrl: https://pcdn.bravesoftware.com/brave-news-ads/0f61aa5e-d79f-4585-9835-b75afb3343b0.jpg.pad
  dimensions: 900x750
  ctaText: Aspect Ratio
  targetUrl: https://brave.com/careers/

```

</details>

#### catalog - dailyCap

<details>


```
[11583:11583:0403/180458.110012:VERBOSE2:exclusion_rules_base.cc(100)] campaignId d1e25388-b362-4f30-bd4b-36b8205e59e5 has exceeded the dailyCap frequency cap
```

released:
```
[11953:11953:0404/180709.631005:VERBOSE1:notification_ad_handler.cc(184)] Served notification ad:
  placementId: 21eaddcc-1225-48a6-8ee8-8f6dfe9ba311
  creativeInstanceId: 4cda3ae7-1f70-4bca-b361-ca01d6a8f1ed
  creativeSetId: 5f8c4787-8431-49a5-9d09-bba40f8ad5f4
  campaignId: d1e25388-b362-4f30-bd4b-36b8205e59e5
  advertiserId: a34de75d-5654-4331-8713-8f4d4e2b6bf7
  segment: untargeted
  title: https://brave.com/
  body: https://brave.com/
  targetUrl: https://brave.com/

```

</details>

#### catalog - perDay

<details>

```
[13435:13435:0403/181420.335270:VERBOSE2:exclusion_rules_base.cc(100)] creativeSetId 5f8c4787-8431-49a5-9d09-bba40f8ad5f4 has exceeded the perDay frequency cap
```

released:
```
[13748:13748:0404/181519.725532:VERBOSE1:notification_ad_handler.cc(184)] Served notification ad:
  placementId: 95ea1006-9706-4ad9-ac07-14663f8be05b
  creativeInstanceId: 4cda3ae7-1f70-4bca-b361-ca01d6a8f1ed
  creativeSetId: 5f8c4787-8431-49a5-9d09-bba40f8ad5f4
  campaignId: d1e25388-b362-4f30-bd4b-36b8205e59e5
  advertiserId: a34de75d-5654-4331-8713-8f4d4e2b6bf7
  segment: untargeted
  title: https://brave.com/
  body: https://brave.com/
  targetUrl: https://brave.com/

```

</details>


#### catalog - perWeek

<details>

```
[15212:15212:0403/182135.687176:VERBOSE2:exclusion_rules_base.cc(100)] creativeSetId 5f8c4787-8431-49a5-9d09-bba40f8ad5f4 has exceeded the perWeek frequency cap

```

released
```
[17606:17606:0410/183010.116666:VERBOSE1:notification_ad_handler.cc(184)] Served notification ad:
  placementId: 7ee51273-6e8f-42a4-baac-619d6afb4b59
  creativeInstanceId: 4cda3ae7-1f70-4bca-b361-ca01d6a8f1ed
  creativeSetId: 5f8c4787-8431-49a5-9d09-bba40f8ad5f4
  campaignId: d1e25388-b362-4f30-bd4b-36b8205e59e5
  advertiserId: a34de75d-5654-4331-8713-8f4d4e2b6bf7
  segment: untargeted
  title: https://brave.com/
  body: https://brave.com/
  targetUrl: https://brave.com/

```


</details>

#### catalog - perMonth

<details>

```
[19205:19205:0403/183957.246194:VERBOSE2:exclusion_rules_base.cc(100)] creativeSetId 5f8c4787-8431-49a5-9d09-bba40f8ad5f4 has exceeded the perMonth frequency cap

```

released
```
[19939:19939:0504/184019.792545:VERBOSE1:notification_ad_handler.cc(184)] Served notification ad:
  placementId: 48f8a7da-15e2-4ccb-86aa-cc85782e6f9e
  creativeInstanceId: 4cda3ae7-1f70-4bca-b361-ca01d6a8f1ed
  creativeSetId: 5f8c4787-8431-49a5-9d09-bba40f8ad5f4
  campaignId: d1e25388-b362-4f30-bd4b-36b8205e59e5
  advertiserId: a34de75d-5654-4331-8713-8f4d4e2b6bf7
  segment: untargeted
  title: https://brave.com/
  body: https://brave.com/
  targetUrl: https://brave.com/

```


</details>

#### catalog - totalMax

<details>

```
[22097:22097:0403/184942.851124:VERBOSE2:exclusion_rules_base.cc(100)] creativeSetId 5f8c4787-8431-49a5-9d09-bba40f8ad5f4 has exceeded the totalMax frequency cap

```




</details>
