### ISSUE TITLE
Clamp property seems to lag on inspector resize

### ISSUE THREAD

**Issue by shinze** [brave/brave-browser#23874]
## Description 

I’m working on a website using proportional font sizes using css clamp property and when I’m inspecting the page with the responsive view activated, resizing the viewport seems really slow.

## Steps to Reproduce

   1. Create any webpage and CSS using clamp property set on the html selector as this :
```css
html {
  font-family: Segoe UI,system-ui,-apple-system,sans-serif;
  line-height: 1.5;
  font-smoothing: antialiased;
  -webkit-font-smoothing: antialiased;
  box-sizing: border-box;
  display: flex;
  justify-content: center;
  font-size: clamp(0.8125rem, 0.6195rem + 1.0294vw, 1.25rem);
}
```
   2. Show the inspector and activate responsive view;
   3. Resize the viewport of the preview window, enjoy.

## Actual result:

The resize action lags.

## Expected result:
No lag.

## Brave version (brave://version info)

```
[Version 1.40.107 Chromium: 103.0.5060.53 (Build officiel) (arm64)](https://brave.com/latest/)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?
