### ISSUE TITLE
Frequency capping are not applied in 1.51.x

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#29867]
`ads per hour` and `ads per day` are not applied

## Steps to Reproduce

1. Clean profile
1. Run Brave with 
```
--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/bat_ads/*"=6 --variations-server-url=https://test --enable-features=AdServing:maximum_new_tab_page_ads_per_day/0/ad_serving_version/2 --rewards=staging=true --use-dev-goupdater-url
```
1. Enable rewards and ads
1. Trigger NTP SI

## Actual result:
NTP SI ad is served
```
[32234:32234:0419/163808.190171:VERBOSE1:eligible_new_tab_page_ads_v2.cc(114)] 4 eligible ads out of 4 ads
[32234:32234:0419/163808.190451:VERBOSE1:new_tab_page_ad_handler.cc(65)] Opportunity arose to serve a new tab page ad
[32234:32234:0419/163808.190650:VERBOSE1:new_tab_page_ad_serving.cc(91)] Found 1 eligible ads
[32234:32234:0419/163808.191013:VERBOSE1:new_tab_page_ad_serving.cc(126)] Served new tab page ad:
  placementId: bd148e15-42a1-4c24-b5d9-3b6714458650
  creativeInstanceId: f7ceed9a-121a-434f-b35a-278edf3a0e09
  creativeSetId: 46cf9cc5-4932-4440-9aca-96ce04c73aa2
  campaignId: 0c281843-7d8b-40f1-9bb9-91d4e74ff5a4
  advertiserId: 803953a8-56b4-4d4b-942a-fa81357f1427
  segment: untargeted
  companyName: BMW
  imageUrl: https://mobile-data-dev.s3.brave.software/assets/ntp-si/69aa9044-d6d2-4e24-ac03-958391b2bb7a.png
  alt: BMW
  targetUrl: https://www.bmwusa.com/?brave-creative-id=%%CREATIVE_INSTANCE%%&source=image3
  wallpaper:
    imageUrl: https://mobile-data-dev.s3.brave.software/assets/ntp-si/a4fb0b72-5362-44a9-ad94-94d653761bf9.jpg
    focalPoint:
      x: 1232
      y: 720
```

## Expected result:
Ad is blocked
```
[1247:1247:0419/164138.621987:VERBOSE2:permission_rule_util.cc(25)] You have exceeded the allowed new tab page ads per day
[1247:1247:0419/164138.629303:VERBOSE1:new_tab_page_ad_serving.cc(65)] New tab page ad not served: Not allowed due to permission rules

```

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.51.96 Chromium: 112.0.5615.121 (Official Build) beta (64-bit)
-- | --
Revision | 39cc4e45904ae9f1741c4fbaa866e629c96f2268-refs/branch-heads/5615_51@{#8}
OS | Ubuntu 18.04 LTS

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes 
- Can you reproduce this issue with the nightly channel? yes

cc @tmancey @aseren
