### ISSUE TITLE
Broken icon/graphics rendering (Wayland)

### ISSUE THREAD

**Issue by maxwelljens** [brave/brave-browser#35034]
## Description 

SVG, CSS graphics, images, and icon rendering is sporadic or entirely non-functional.

## Steps to Reproduce

   1. Run a Wayland session
   2. Open Brave
   3. Browse any website

### www.bing.com
![image](https://github.com/brave/brave-browser/assets/85795372/6aa2ae0f-9847-4679-a629-e1588445eeb8)
### www.hyprland.org
![image](https://github.com/brave/brave-browser/assets/85795372/1f4a4021-86d0-4aa6-b5f2-b56077a9c216)

## Expected result:
Proper rendering.

## Reproduces how often: 

Reproduced only when running a Wayland desktop session. Issue does not persist when using an X11 session, such as bspwm. This issue did not happen until today (23rd December 2023).

## Brave version (brave://version info)

```
Brave	1.61.109 Chromium: 120.0.6099.144 (Official Build) (64-bit) 
Revision	ea6e204b94e25f08d7a80301c88ba8d2bf96502f
OS	Linux
JavaScript	V8 12.0.267.10
User agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Command Line	/opt/brave.com/brave/brave --disable-domain-reliability --enable-distillability-service --enable-dom-distiller --lso-url=https://no-thanks.invalid --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --ozone-platform=wayland --restart --sync-url=https://sync-v2.brave.com/v2 --variations-insecure-server-url=https://variations.brave.com/seed --variations-server-url=https://variations.brave.com/seed --restart --flag-switches-begin --ozone-platform-hint=auto --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions,url-source=https://go-updater.brave.com/extensions,url-source=https://go-updater.brave.com/extensions,url-source=https://go-updater.brave.com/extensions
Executable Path	/opt/brave.com/brave/brave
Profile Path	/home/maxwellj/.config/BraveSoftware/Brave-Browser/Default
Active variations	AllowCertainClientHintsStudy:Enabled
BraveAIChatEnabledStudy:Enabled
BraveAdblockMobileNotificationsListDefault:Enabled
BraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=6/MaximumInlineContentAdsPerDay=20/AdServingVersion=2
BraveAutoTranslateStudy:AutoTranslateDisabled
BraveDebounceStudy:Enabled
BraveForgetFirstPartyStorage:Enabled
BraveGoogleSignInPermissionStudy:Disabled
BraveHttpsByDefaultRolloutStudy:Enabled
BraveP3AConstellationReleaseRollout:Enabled
BraveRewardsWebUiPanelStudy:Enabled
BraveScreenFingerprintingBlockerStudy:Enabled
BraveSearchAdStudy:EnabledInProcessDesktop
ClampPlatformVersionClientHint:Disabled
CookieListDefaultStudy:Enabled
Default1pBlockingStudy:Disabled
DisableReduceLanguage:Enabled
EphemeralStorageStudy:Enabled
FirstPartyEphemeralDomainBlockStudy:Enabled
ForceDisableBlinkFeatures:Enabled
PartitionBlinkMemoryCacheStudy:Enabled
PartitionConnectionsByNetworkIsolationKeyStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
SmilAutoSuspendOnLagKillSwitch:Disabled_EmergencyKillSwitch
UserActivityStudy:Triggers
WhatsNewStudy:Enabled
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes
- Can you reproduce this issue with the beta channel?
Unknown
- Can you reproduce this issue with the nightly channel?
Unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome?
Unknown

## Miscellaneous Information:

Output of `inxi` for system :
```
System:
  Host: fedora Kernel: 6.6.7-200.fc39.x86_64 arch: x86_64 bits: 64
    Desktop: Hyprland Distro: Fedora release 39 (Thirty Nine)
Graphics:
  Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
    driver: amdgpu v: kernel
  Display: wayland server: X.org v: 1.20.14 with: Xwayland v: 23.2.3
    compositor: Hyprland driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi gpu: amdgpu
    resolution: 1: 1920x1080~144Hz 2: 1920x1080~144Hz
  API: EGL v: 1.5 drivers: radeonsi,swrast
    platforms: wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 23.3.1 renderer: AMD
    Radeon RX 5600 XT (radeonsi navi10 LLVM 17.0.6 DRM 3.54
    6.6.7-200.fc39.x86_64)
```
Running Hyprland 0.33.1 (https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/)

**Comment by rebron** [comment]
cc: @wknapik @rillian

**Comment by oxgl** [comment]
Hello! 
I have a similar issue. When I execute Brave browser immediately after logging into Gnome Wayland session, Brave shows layout of the website with images but without text:
![before](https://github.com/brave/brave-browser/assets/35221549/9ccf64f0-8f10-49e9-b72c-d96730405973)

Then I close Brave, wait few seconds and execute Brave again. Now, everything is displayed properly:
![after](https://github.com/brave/brave-browser/assets/35221549/17534c6b-b927-4ffd-a4f7-0146ea1a6fc5)

inxi:
```
System:
  Host: pc Kernel: 6.6.8-200.fc39.x86_64 arch: x86_64 bits: 64
    Desktop: GNOME v: 45.2 Distro: Fedora release 39 (Thirty Nine)
Graphics:
  Device-1: AMD Navi 33 [Radeon RX 7700S/7600/7600S/7600M XT/PRO W7600]
    driver: amdgpu v: kernel
  Display: wayland server: X.Org v: 23.2.3 with: Xwayland v: 23.2.3
    compositor: gnome-shell driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi gpu: amdgpu
    resolution: 2560x1440~60Hz
  API: EGL v: 1.5 drivers: kms_swrast,radeonsi,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 23.3.1 renderer: AMD
    Radeon RX 7600 (radeonsi navi33 LLVM 17.0.6 DRM 3.54
    6.6.8-200.fc39.x86_64)
  API: Vulkan v: 1.3.268 drivers: radv,llvmpipe surfaces: xcb,xlib,wayland
```
Thank you!
