### ISSUE TITLE
[ads] Initial new tab takeover ad is not shown for Brave Rewards users if the browser is restarted when the last active tab is a new tab

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#35840]
The NTPSI is served but not shown when expected. Needs additional NTP to be shown

## Steps to Reproduce

1. Clean profile
1. Enable rewards and ads
1. Open NTP
1. Restart Brave
1. Open NTP till NTP SI is shown

## Actual result:

It takes 4 NTP for NTP SI to be shown 

![image](https://github.com/brave/brave-browser/assets/34715963/c12ee510-9e43-4e17-b39a-2307ca6341df)

![ntpsi](https://github.com/brave/brave-browser/assets/34715963/a526f61b-6929-4247-bb5b-7ec7a2998169)

The NTPSI is served on first NTP
```
[20654:20654:0206/203451.646687:VERBOSE1:new_tab_page_ad_handler.cc(151)] Opportunity arose to serve a new tab page ad
[20654:20654:0206/203451.647302:VERBOSE1:text_classification_model.cc(74)] No text classification probabilities found for en_US.UTF-8 locale
[20654:20654:0206/203451.647804:VERBOSE1:eligible_new_tab_page_ads_v2.cc(38)] Get eligible new tab page ads
[20654:20654:0206/203451.671567:VERBOSE1:new_tab_page_ad_serving.cc(95)] Found 1 eligible ads
[20654:20654:0206/203451.672071:VERBOSE1:new_tab_page_ad_handler.cc(172)] Served new tab page ad:
  placementId: 7a125d3e-bfb9-45ee-b247-13be2583f22d
  creativeInstanceId: f7ceed9a-121a-434f-b35a-278edf3a0e09
  creativeSetId: 46cf9cc5-4932-4440-9aca-96ce04c73aa2
  campaignId: 0c281843-7d8b-40f1-9bb9-91d4e74ff5a4
  advertiserId: 803953a8-56b4-4d4b-942a-fa81357f1427
  segment: untargeted
  companyName: BMW
  imageUrl: https://mobile-data-dev.s3.brave.software/assets/ntp-si/69aa9044-d6d2-4e24-ac03-958391b2bb7a.png
  alt: BMW
  targetUrl: https://www.bmwusa.com/?brave-creative-id=f7ceed9a-121a-434f-b35a-278edf3a0e09&source=image3
  wallpaper:
    imageUrl: https://mobile-data-dev.s3.brave.software/assets/ntp-si/a4fb0b72-5362-44a9-ad94-94d653761bf9.jpg
    focalPoint:
      x: 1232
      y: 720
[20654:20654:0206/203451.701613:VERBOSE3:new_tab_page_ad_handler.cc(179)] Served new tab page ad with placement id 7a125d3e-bfb9-45ee-b247-13be2583f22d and creative instance id f7ceed9a-121a-434f-b35a-278edf3a0e09

```

## Expected result:
NTP SI is shown on 2nd NTP

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.62.161 Chromium: 121.0.6167.139 (Official Build) (64-bit)
-- | --
Revision | 9afaacd1500fdbd60ed4500b63b9ab85597ef933
OS | Linux

Brave | 1.64.55 Chromium: 121.0.6167.164 (Official Build) nightly (64-bit)
-- | --
Revision | b6025f4892ad4674e751eccbb6e61c9aa7bbd1c4
OS | Linux

cc @tmancey @aseren @iambrianfung @LaurenWags
