### ISSUE TITLE
[ads] Auto-vacuum database

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#37549]

**Comment by btlechowski** [comment]
Verified on

Brave | 1.71.105 Chromium: 129.0.6668.89 (Official Build) beta (64-bit)
-- | --
Revision | f69ba167992437799f1dbcce81e90ba501a3d63e
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/25133


#### clean install - notification ad

<details>

Verified ad is served
```
[22451:22451:1006/135523.799324:VERBOSE3:notification_ad_handler.cc(187)] Served notification ad impression with placement id 2cf5281c-632b-400e-b8bb-5228c667a523 and creative instance id 4cda5cb7-c4f8-4cbc-8898-58de12ece304
[22451:22451:1006/135523.820679:VERBOSE3:notification_ad_handler.cc(194)] Viewed notification ad impression with placement id 2cf5281c-632b-400e-b8bb-5228c667a523 and creative instance id 4cda5cb7-c4f8-4cbc-8898-58de12ece304

```

</details>


#### clean install - NTT

<details>


Verified ad is served
```
[22451:22451:1006/135557.772684:VERBOSE1:new_tab_page_ad_handler.cc(171)] Served new tab page ad impression:
  placementId: 2653be3a-3288-46fa-91cd-39cb2eb56f7e
  creativeInstanceId: a99b9a02-3d90-462a-9fc1-2e78249ee479
  creativeSetId: 19bdbe19-9615-460d-bd2d-46419442f196
  campaignId: 3c8f17f6-a16d-42c0-9ef5-42d1095cd783
  advertiserId: 803953a8-56b4-4d4b-942a-fa81357f1427
  segment: untargeted
  companyName: Brave - The image is a 2560x2560 square
  imageUrl: https://mobile-data-dev.s3.brave.software/assets/ntp-si/bb09d0de-d0e9-4387-a406-d8261255de7c.png
  alt: The image is a 2560x2560 square.
  targetUrl: https://brave.com/?source=image3
  wallpaper:
    imageUrl: https://mobile-data-dev.s3.brave.software/assets/ntp-si/25eeeca6-1707-40ed-98eb-51d51a7d5cf2.jpg
    focalPoint:
      x: 1280
      y: 720
[22451:22451:1006/135557.813506:VERBOSE3:new_tab_page_ad_handler.cc(178)] Served new tab page ad impression with placement id 2653be3a-3288-46fa-91cd-39cb2eb56f7e and creative instance id a99b9a02-3d90-462a-9fc1-2e78249ee479
[22451:22451:1006/135600.872182:VERBOSE3:new_tab_page_ad_handler.cc(185)] Viewed new tab page ad impression with placement id 2653be3a-3288-46fa-91cd-39cb2eb56f7e and creative instance id a99b9a02-3d90-462a-9fc1-2e78249ee479

```


</details>


#### clean install - Brave News inline ad

<details>


Verified ad is served
```
[22451:22451:1006/135705.653414:VERBOSE1:inline_content_ad_handler.cc(185)] Served inline content ad:
  placementId: 9fbcf39c-25da-4ed1-ac03-3fb1e2e5d6ef
  creativeInstanceId: 211a9ff9-48bf-4b79-bd2a-f6b450edac0a
  creativeSetId: 8b848823-c47f-43de-a753-2efa8dea6863
  campaignId: 07de7f05-ab32-4af0-a350-a1bce4427eac
  advertiserId: 93130af3-2def-4ecb-b836-b3772e73b3c9
  segment: untargeted
  title: [Staging] Aspect Ratio
  description: Test Aspect Ratio
  imageUrl: https://pcdn.bravesoftware.com/brave-news-ads/0f61aa5e-d79f-4585-9835-b75afb3343b0.jpg.pad
  dimensions: 900x750
  ctaText: Aspect Ratio
  targetUrl: https://brave.com/careers/
[22451:22451:1006/135705.734334:VERBOSE3:inline_content_ad_handler.cc(192)] Served inline content ad impression with placement id 9fbcf39c-25da-4ed1-ac03-3fb1e2e5d6ef and creative instance id 211a9ff9-48bf-4b79-bd2a-f6b450edac0a
[22451:22451:1006/135712.072613:VERBOSE3:inline_content_ad_handler.cc(199)] Viewed inline content ad impression with placement id 9fbcf39c-25da-4ed1-ac03-3fb1e2e5d6ef and creative instance id 211a9ff9-48bf-4b79-bd2a-f6b450edac0a

```


</details>


#### clean install - Brave Search ad

<details>


Verified ad is served
```
[22451:22451:1006/140150.094823:VERBOSE3:search_result_ad_handler.cc(168)] Served search result ad impression with placement id 13b638c4-acec-4a43-8a0c-5c7d76d93419 and creative instance id 788a9319-9ff9-4cf8-944b-98dcdc3dbfa8
[22451:22451:1006/140150.336080:VERBOSE3:search_result_ad_handler.cc(175)] Viewed search result ad impression with placement id 13b638c4-acec-4a43-8a0c-5c7d76d93419 and creative instance id 788a9319-9ff9-4cf8-944b-98dcdc3dbfa8

```


</details>
