### ISSUE TITLE
[ads] Refactor database `BindInt64` to `BindTime`, `BindTimeDelta` and `TimeToSqlValue`

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#39801]
See `src/sql/statement.h`

**Comment by btlechowski** [comment]
Verified on

Brave | 1.71.105 Chromium: 129.0.6668.89 (Official Build) beta (64-bit)
-- | --
Revision | f69ba167992437799f1dbcce81e90ba501a3d63e
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/25137

#### confirmation queue

<details>

Verified confirmation is created:
```
[25035:25035:1006/160756.390485:VERBOSE1:redeem_reward_confirmation.cc(77)] Redeem reward confirmation
[25035:25035:1006/160756.393251:VERBOSE1:redeem_reward_confirmation.cc(92)] Create reward confirmation
[25035:25035:1006/160756.393601:VERBOSE6:redeem_reward_confirmation.cc(96)] URL Request:
  URL: https://anonymous.ads.bravesoftware.com/v3/confirmation/8a32687f-ef7b-408e-92cf-ae1eedf1eb27/eyJzaWduYXR1cmUiOiJiQmJrSjhyY1Zua3Z6ckZyQ2Z2eG8xOXErNnJPRDgrMjBSRDh0T2V3YlFaY252ZW1IYlBYc1YrK1NNTzRveGtIL2dOYllvZWxNTUtJUzhWU2R1d1VTZz09IiwidCI6IkFyTTkySVdodlZsUlhwQk9OQ0lGeE9VVXJib01oN24vcXhDVTRhNEtDNUg2c2x1bkM2KytGRVJhQWxxbUJRVlkwRDZEMnZ4MnorQkQ2OHNNaHdQSUZRPT0ifQ==
  Content: {"blindedPaymentTokens":["gFCpg+pW9RmFG+CwD7/GBEqB79TGROeYpkStyhj0XTI="],"buildChannel":"beta","catalog":[{"id":"YV9x0iWWerBwvU/bT4DVXCynLNI2dW6MSdBqg104gso="}],"createdAtTimestamp":"2024-10-06T14:00:00.000Z","creativeInstanceId":"94464eab-dae5-4e4e-9d93-d5b2d0aeb724","platform":"linux","publicKey":"wgMhKwj/Vs832efOg+RlqJvLy3Ta3UDbz1wV+Z+dzEU=","rotatingHash":"vg2+QnNk70Ha1CAbd2DPVB+6MULUdx4vBhvgSJ+uv6U=","segment":"untargeted","studies":[],"systemTimestamp":"2024-10-06T14:00:00.000Z","transactionId":"8a32687f-ef7b-408e-92cf-ae1eedf1eb27","type":"view","versionNumber":"129.0.6668.89"}
  Content Type: application/json
  Method: kPost
[25035:25035:1006/160756.393633:VERBOSE7:redeem_reward_confirmation.cc(97)]   Headers:
    accept: application/json
[25035:25035:1006/160757.744578:VERBOSE6:redeem_reward_confirmation.cc(110)] URL Response:
  URL: https://anonymous.ads.bravesoftware.com/v3/confirmation/8a32687f-ef7b-408e-92cf-ae1eedf1eb27/eyJzaWduYXR1cmUiOiJiQmJrSjhyY1Zua3Z6ckZyQ2Z2eG8xOXErNnJPRDgrMjBSRDh0T2V3YlFaY252ZW1IYlBYc1YrK1NNTzRveGtIL2dOYllvZWxNTUtJUzhWU2R1d1VTZz09IiwidCI6IkFyTTkySVdodlZsUlhwQk9OQ0lGeE9VVXJib01oN24vcXhDVTRhNEtDNUg2c2x1bkM2KytGRVJhQWxxbUJRVlkwRDZEMnZ4MnorQkQ2OHNNaHdQSUZRPT0ifQ==
  Response Status Code: 201
  Response: {"id":"8a32687f-ef7b-408e-92cf-ae1eedf1eb27","payload":{},"type":"view","createdAt":"2024-10-06T14:07:58.024Z","modifiedAt":"2024-10-06T14:07:58.024Z","creativeInstanceId":"94464eab-dae5-4e4e-9d93-d5b2d0aeb724"}
[25035:25035:1006/160757.744722:VERBOSE7:redeem_reward_confirmation.cc(111)]   Headers:
    accept-ranges: bytes
    access-control-allow-credentials: true
    content-length: 211
    content-security-policy: sandbox
    content-type: application/json; charset=utf-8
    cross-origin-opener-policy: same-origin
    cross-origin-resource-policy: same-origin
    date: Sun, 06 Oct 2024 14:07:58 GMT
    referrer-policy: same-origin
    strict-transport-security: max-age=31536000; includeSubDomains; preload
    vary: Origin, Accept-Encoding
    via: 1.1 varnish
    x-cache: MISS
    x-cache-hits: 0
    x-content-type-options: nosniff
    x-frame-options: DENY
    x-served-by: cache-cph2320043-CPH

```

Verified the confirmation is fetched after 15s
```
[25035:25035:1006/160757.744743:VERBOSE1:redeem_reward_confirmation.cc(122)] Fetch payment token in 15 s
[25035:25035:1006/160812.753977:VERBOSE1:redeem_reward_confirmation.cc(135)] Fetch payment token
[25035:25035:1006/160812.754139:VERBOSE6:redeem_reward_confirmation.cc(139)] URL Request:
  URL: https://anonymous.ads.bravesoftware.com/v3/confirmation/8a32687f-ef7b-408e-92cf-ae1eedf1eb27/paymentToken
  Method: kGet
[25035:25035:1006/160812.754204:VERBOSE7:redeem_reward_confirmation.cc(140)]   Headers:

[25035:25035:1006/160813.002208:VERBOSE6:redeem_reward_confirmation.cc(153)] URL Response:
  URL: https://anonymous.ads.bravesoftware.com/v3/confirmation/8a32687f-ef7b-408e-92cf-ae1eedf1eb27/paymentToken
  Response Status Code: 200
  Response: {"id":"8a32687f-ef7b-408e-92cf-ae1eedf1eb27","type":"view","createdAt":"2024-10-06T14:07:58.024Z","modifiedAt":"2024-10-06T14:08:00.438Z","creativeInstanceId":"94464eab-dae5-4e4e-9d93-d5b2d0aeb724","paymentToken":{"publicKey":"BF4cfMiT9ph89IO1oZf7wrKQeX0YW/Hq2T1CyriXc0E=","batchProof":"3Rnll6G4yTS/TO8U9boSi3vCwVkkji/4Zg7aQkknngyMduyViqV7gvBLH7zBEa6VvZO6+V1AwQTVB96Lvw7hBA==","signedTokens":["kO3+B/jMLmQzwpus5pcukc4DvDp/fT+p87bisHmzayY="]}}
[25035:25035:1006/160813.002323:VERBOSE7:redeem_reward_confirmation.cc(154)]   Headers:
    accept-ranges: bytes
    access-control-allow-credentials: true
    content-length: 442
    content-security-policy: sandbox
    content-type: application/json; charset=utf-8
    cross-origin-opener-policy: same-origin
    cross-origin-resource-policy: same-origin
    date: Sun, 06 Oct 2024 14:08:13 GMT
    referrer-policy: same-origin
    strict-transport-security: max-age=31536000; includeSubDomains; preload
    vary: Origin, Accept-Encoding
    via: 1.1 varnish
    x-cache: MISS
    x-cache-hits: 0
    x-content-type-options: nosniff
    x-frame-options: DENY
    x-served-by: cache-cph2320043-CPH

```



</details>

#### confirmation queue - 503 error

<details>

Verified the confirmation is rescheduled
```
[25035:25035:1006/161626.825926:VERBOSE1:confirmations.cc(83)] Process kViewedImpression confirmation for kInlineContentAd with transaction id ca30854f-9994-472b-8732-75d2e7952ca3 and creative instance id b532b1f6-2c0b-4dd6-8a98-b4f38068eba0 in 0 hours, 0 minutes, 5 seconds at 16:16:31.823

```


</details>


#### user rewards

<details>

Verified user is rewarded

```
[26695:26695:1006/164408.483769:VERBOSE1:confirmations.cc(92)] Successfully processed kViewedImpression confirmation for kInlineContentAd with transaction id 255cd8d3-bba9-4642-baf2-d12fed3bd0b9 and creative instance id 22110568-4125-4b84-b97a-27ef45c5c07c

```


</details>

#### statement of accounts on brave://rewards

<details>

Verified statement increases with ads delivered

![image](https://github.com/user-attachments/assets/6d3acc7f-6b6b-432a-9e29-eece4b155905)|![image](https://github.com/user-attachments/assets/bbb05732-ace3-436b-8173-94e85023af91)
--|--


</details>


#### ad delivery

<details>

#### notification ad

<details>

Verified ad is served
```
[22451:22451:1006/135523.799324:VERBOSE3:notification_ad_handler.cc(187)] Served notification ad impression with placement id 2cf5281c-632b-400e-b8bb-5228c667a523 and creative instance id 4cda5cb7-c4f8-4cbc-8898-58de12ece304
[22451:22451:1006/135523.820679:VERBOSE3:notification_ad_handler.cc(194)] Viewed notification ad impression with placement id 2cf5281c-632b-400e-b8bb-5228c667a523 and creative instance id 4cda5cb7-c4f8-4cbc-8898-58de12ece304

```

</details>


#### NTT

<details>


Verified ad is served
```
[22451:22451:1006/135557.772684:VERBOSE1:new_tab_page_ad_handler.cc(171)] Served new tab page ad impression:
  placementId: 2653be3a-3288-46fa-91cd-39cb2eb56f7e
  creativeInstanceId: a99b9a02-3d90-462a-9fc1-2e78249ee479
  creativeSetId: 19bdbe19-9615-460d-bd2d-46419442f196
  campaignId: 3c8f17f6-a16d-42c0-9ef5-42d1095cd783
  advertiserId: 803953a8-56b4-4d4b-942a-fa81357f1427
  segment: untargeted
  companyName: Brave - The image is a 2560x2560 square
  imageUrl: https://mobile-data-dev.s3.brave.software/assets/ntp-si/bb09d0de-d0e9-4387-a406-d8261255de7c.png
  alt: The image is a 2560x2560 square.
  targetUrl: https://brave.com/?source=image3
  wallpaper:
    imageUrl: https://mobile-data-dev.s3.brave.software/assets/ntp-si/25eeeca6-1707-40ed-98eb-51d51a7d5cf2.jpg
    focalPoint:
      x: 1280
      y: 720
[22451:22451:1006/135557.813506:VERBOSE3:new_tab_page_ad_handler.cc(178)] Served new tab page ad impression with placement id 2653be3a-3288-46fa-91cd-39cb2eb56f7e and creative instance id a99b9a02-3d90-462a-9fc1-2e78249ee479
[22451:22451:1006/135600.872182:VERBOSE3:new_tab_page_ad_handler.cc(185)] Viewed new tab page ad impression with placement id 2653be3a-3288-46fa-91cd-39cb2eb56f7e and creative instance id a99b9a02-3d90-462a-9fc1-2e78249ee479

```


</details>


#### Brave News inline ad

<details>


Verified ad is served
```
[22451:22451:1006/135705.653414:VERBOSE1:inline_content_ad_handler.cc(185)] Served inline content ad:
  placementId: 9fbcf39c-25da-4ed1-ac03-3fb1e2e5d6ef
  creativeInstanceId: 211a9ff9-48bf-4b79-bd2a-f6b450edac0a
  creativeSetId: 8b848823-c47f-43de-a753-2efa8dea6863
  campaignId: 07de7f05-ab32-4af0-a350-a1bce4427eac
  advertiserId: 93130af3-2def-4ecb-b836-b3772e73b3c9
  segment: untargeted
  title: [Staging] Aspect Ratio
  description: Test Aspect Ratio
  imageUrl: https://pcdn.bravesoftware.com/brave-news-ads/0f61aa5e-d79f-4585-9835-b75afb3343b0.jpg.pad
  dimensions: 900x750
  ctaText: Aspect Ratio
  targetUrl: https://brave.com/careers/
[22451:22451:1006/135705.734334:VERBOSE3:inline_content_ad_handler.cc(192)] Served inline content ad impression with placement id 9fbcf39c-25da-4ed1-ac03-3fb1e2e5d6ef and creative instance id 211a9ff9-48bf-4b79-bd2a-f6b450edac0a
[22451:22451:1006/135712.072613:VERBOSE3:inline_content_ad_handler.cc(199)] Viewed inline content ad impression with placement id 9fbcf39c-25da-4ed1-ac03-3fb1e2e5d6ef and creative instance id 211a9ff9-48bf-4b79-bd2a-f6b450edac0a

```


</details>


#### Brave Search ad

<details>


Verified ad is served
```
[22451:22451:1006/140150.094823:VERBOSE3:search_result_ad_handler.cc(168)] Served search result ad impression with placement id 13b638c4-acec-4a43-8a0c-5c7d76d93419 and creative instance id 788a9319-9ff9-4cf8-944b-98dcdc3dbfa8
[22451:22451:1006/140150.336080:VERBOSE3:search_result_ad_handler.cc(175)] Viewed search result ad impression with placement id 13b638c4-acec-4a43-8a0c-5c7d76d93419 and creative instance id 788a9319-9ff9-4cf8-944b-98dcdc3dbfa8

```


</details>


</details>


#### ad conversions

<details>

#### notification ad

```

```

#### NTT

```

```

#### Brave News inline ad

```

```


#### Search ads

```

```





</details>

#### frequency capping

<details>




</details>
