### ISSUE TITLE
[QA] Rewards 3.0 desktop full end-to-end testing

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#42206]
## Description

This is a tracking issue for the full Rewards 3.0 end-to-end testing. Up until now, different parts of Rewards 3.0 have been tested as they've come in. This issue is to track the full end-to-end QA of Rewards 3.0 before it is enabled for users via Griffin.

_**Refer to test cases document.**_ @Miyayes

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.75.154 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | 2e3d87550a56a852efde889223183dc3b456791e
OS | Windows 10 Version 22H2 (Build 19045.5247)

```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.75.165 Chromium: 132.0.6834.83 (Official Build) beta (x86_64)
-- | --
Revision | 64f812b6a1efa52daa39e34d2876dc0b4313b446
OS | macOS Version 14.7.2 (Build 23H311)
```

**Comment by btlechowski** [comment]
Verified with

Brave | 1.75.170 Chromium: 132.0.6834.111 (Official Build) beta (64-bit)
-- | --
Revision | ea6b6fa547193f9769ffb0068880a4f41e364864
OS | Linux


### Clean profile - non-connected - rewards

#### Notification ad - enabled

<details>

Verified ad is served

```
[66630:66630:0130/191435.810383:VERBOSE3:priority_util.h(23)] 12 untargeted ads with a priority of 1 in bucket 1
[66630:66630:0130/191435.810396:VERBOSE3:priority_util.h(23)] 1 untargeted ads with a priority of 51 in bucket 2
[66630:66630:0130/191435.810413:VERBOSE1:eligible_notification_ads_v2.cc(129)] Predicted ad with creative instance id 10b8a8c1-4308-40f5-b6df-5281cf5ef628 and a priority of 1
[66630:66630:0130/191435.810424:VERBOSE1:notification_ad_serving.cc(152)] Found 1 eligible ads
[66630:66630:0130/191435.810448:VERBOSE1:notification_ad_serving.cc(157)] Chosen eligible ad with creative instance id 10b8a8c1-4308-40f5-b6df-5281cf5ef628 and a priority of 1
[66630:66630:0130/191435.810460:VERBOSE1:notification_ad_handler.cc(175)] Served notification ad impression:
  placementId: e048d631-d054-4910-8101-2abbddcca004
  creativeInstanceId: 10b8a8c1-4308-40f5-b6df-5281cf5ef628
  creativeSetId: 45ea5952-37ca-41f0-88c2-4b546b0e6f4b
  campaignId: 1c1ac828-db13-49bb-9128-090132044b7f
  advertiserId: ecbcc833-8b1d-4867-98f7-ad2341396ce8
  segment: untargeted
  title: Ad1
  body: Ad1
  targetUrl: https://brave.com/
[66630:66630:0130/191435.810587:VERBOSE6:ads_service_impl.cc(887)] Timeout notification ad with placement id e048d631-d054-4910-8101-2abbddcca004 in 120 s
[66630:66630:0130/191435.824558:VERBOSE3:notification_ad_handler.cc(186)] Served notification ad impression with placement id e048d631-d054-4910-8101-2abbddcca004 and creative instance id 10b8a8c1-4308-40f5-b6df-5281cf5ef628

```

View

```
[66630:66630:0130/191435.834960:VERBOSE3:notification_ad_handler.cc(193)] Viewed notification ad impression with placement id e048d631-d054-4910-8101-2abbddcca004 and creative instance id 10b8a8c1-4308-40f5-b6df-5281cf5ef628

```

UI is updated:

![Image](https://github.com/user-attachments/assets/98a6676f-bf61-40d6-855f-c02b681b5a4e)|![Image](https://github.com/user-attachments/assets/169bd557-3b24-48af-b685-c8bd22f271ea)|![Image](https://github.com/user-attachments/assets/4a6ec7f5-2946-4ffe-9d11-48fedfc3d1ce)
--|--|--

</details>

#### Notification ad - disabled

<details>

UI:

![Image](https://github.com/user-attachments/assets/3b9fbbf4-52eb-4edf-84de-5fed89ccd17f)|![Image](https://github.com/user-attachments/assets/052cdf33-7b6b-4997-8e14-7632003c9d34)
--|--

Verified notification ads are not served

</details>

#### Notification ad - ads per hour

<details>

1 per hour:
```
[68348:68348:0130/194135.509078:VERBOSE2:ads_per_hour_permission_rule.cc(18)] You have exceeded the allowed ads per hour
[68348:68348:0130/194135.509139:VERBOSE1:notification_ad_serving.cc(96)] Notification ad not served: Not allowed due to permission rules

```

10 ads per hour:
```
[68348:68348:0130/194239.465156:VERBOSE1:notification_ad_serving.cc(152)] Found 1 eligible ads
[68348:68348:0130/194239.465187:VERBOSE1:notification_ad_serving.cc(157)] Chosen eligible ad with creative instance id 75b64af1-02f3-4c0f-be15-86ffc8212fcd and a priority of 1
[68348:68348:0130/194239.465208:VERBOSE1:notification_ad_handler.cc(175)] Served notification ad impression:
  placementId: bb9597f4-e26f-4202-8dbf-66eb8298929d
  creativeInstanceId: 75b64af1-02f3-4c0f-be15-86ffc8212fcd
  creativeSetId: f8a13907-5c02-4ff9-88dc-933463c77f44
  campaignId: 1c1ac828-db13-49bb-9128-090132044b7f
  advertiserId: ecbcc833-8b1d-4867-98f7-ad2341396ce8
  segment: untargeted
  title: Hello, Brave
  body: Brave AI will one day take over the world
  targetUrl: https://brave.com/
[68348:68348:0130/194239.465397:VERBOSE6:ads_service_impl.cc(887)] Timeout notification ad with placement id bb9597f4-e26f-4202-8dbf-66eb8298929d in 120 s
[68348:68348:0130/194239.481313:VERBOSE3:notification_ad_handler.cc(186)] Served notification ad impression with placement id bb9597f4-e26f-4202-8dbf-66eb8298929d and creative instance id 75b64af1-02f3-4c0f-be15-86ffc8212fcd

```


</details>



#### NTT ad - enabled

<details>

Ad served:

```
[72870:72870:0130/194120.387203:VERBOSE1:new_tab_page_ad_serving.cc(124)] Found 1 eligible ads
[72870:72870:0130/194120.387326:VERBOSE1:new_tab_page_ad_serving.cc(129)] Chosen eligible ad with creative instance id 026a190e-022e-40d1-8ed5-e8f152dfa9b0 and a priority of 51
[72870:72870:0130/194120.387434:VERBOSE1:new_tab_page_ad_handler.cc(170)] Served new tab page ad impression:
  placementId: 96521e85-05ea-49af-b1be-2817a00d1119
  creativeInstanceId: 026a190e-022e-40d1-8ed5-e8f152dfa9b0
  creativeSetId: 46cf9cc5-4932-4440-9aca-96ce04c73aa2
  campaignId: 0c281843-7d8b-40f1-9bb9-91d4e74ff5a4
  advertiserId: 803953a8-56b4-4d4b-942a-fa81357f1427
  segment: untargeted
  companyName: BMW
  imageUrl: https://mobile-data-dev.s3.brave.software/assets/ntp-si/69aa9044-d6d2-4e24-ac03-958391b2bb7a.png
  alt: BMW
  targetUrl: https://www.bmwusa.com/?brave-creative-id=026a190e-022e-40d1-8ed5-e8f152dfa9b0&source=image1
  wallpaper:
    imageUrl: https://mobile-data-dev.s3.brave.software/assets/ntp-si/72ba7af0-160e-4b1b-bdec-5ae0d166f7e1.jpg
    focalPoint:
      x: 756
      y: 720
[72870:72870:0130/194120.400848:VERBOSE3:new_tab_page_ad_handler.cc(177)] Served new tab page ad impression with placement id 96521e85-05ea-49af-b1be-2817a00d1119 and creative instance id 026a190e-022e-40d1-8ed5-e8f152dfa9b0

```


![Image](https://github.com/user-attachments/assets/de0732c1-863c-431a-b891-1d27e78a3fc0)|![Image](https://github.com/user-attachments/assets/5b539009-9d3f-4b11-aab8-23acfefb218e)
--|--

</details>


#### NTT ad - disabled

<details>

![Image](https://github.com/user-attachments/assets/785283e2-18f2-40ee-8611-eaa64d8605c4)|![Image](https://github.com/user-attachments/assets/3441b7fc-e8d0-4438-992c-bb92bd803f46)
--|--

Verified ads are not served

</details>


#### Brave News Inline ad - enabled

<details>


```
[71115:71115:0130/193208.337046:VERBOSE1:inline_content_ad_handler.cc(183)] Served inline content ad:
  placementId: d6316163-1ed6-42b5-9416-a76ec8239fb5
  creativeInstanceId: 211a9ff9-48bf-4b79-bd2a-f6b450edac0a
  creativeSetId: 8b848823-c47f-43de-a753-2efa8dea6863
  campaignId: 07de7f05-ab32-4af0-a350-a1bce4427eac
  advertiserId: 93130af3-2def-4ecb-b836-b3772e73b3c9
  segment: untargeted
  title: [Staging] Aspect Ratio
  description: Test Aspect Ratio
  imageUrl: https://pcdn.bravesoftware.com/brave-news-ads/0f61aa5e-d79f-4585-9835-b75afb3343b0.jpg.pad
  dimensions: 900x750
  ctaText: Aspect Ratio
  targetUrl: https://brave.com/careers/
[71115:71115:0130/193208.359030:VERBOSE3:inline_content_ad_handler.cc(190)] Served inline content ad impression with placement id d6316163-1ed6-42b5-9416-a76ec8239fb5 and creative instance id 211a9ff9-48bf-4b79-bd2a-f6b450edac0a

```

UI:

![Image](https://github.com/user-attachments/assets/4d34e6dd-97b7-4607-8fc6-dc144a870059)|![Image](https://github.com/user-attachments/assets/92a7d8ce-fcf4-420a-94ea-77774ea1beb5)
--|--

</details>



#### Brave search ad - enabled

<details>

Served and viewed
```
[72870:72870:0130/194705.850611:VERBOSE3:search_result_ad_handler.cc(167)] Served search result ad impression with placement id b731b6e9-4fb9-474e-98bc-ff9544753ccf and creative instance id c2f2dace-d356-4bce-b5c9-cae75f2bd2aa
[72870:72870:0130/194705.868624:VERBOSE3:search_result_ad_event_handler.cc(156)] Successfully saved search result ad deposit
[72870:72870:0130/194705.868698:VERBOSE1:conversions.cc(122)] There are no matching creative set conversions
[72870:72870:0130/194705.891557:VERBOSE3:search_result_ad_handler.cc(174)] Viewed search result ad impression with placement id b731b6e9-4fb9-474e-98bc-ff9544753ccf and creative instance id c2f2dace-d356-4bce-b5c9-cae75f2bd2aa

```

UI:

![Image](https://github.com/user-attachments/assets/91f719d0-3a69-4650-8193-658e3cc453e5)|![Image](https://github.com/user-attachments/assets/ab7a7f83-8d54-41a6-b6e9-a2205d9b6f48)|![Image](https://github.com/user-attachments/assets/7048b446-c101-4285-a8d6-a2d876a9a4bf)
--|--|--

</details>


#### Brave search ad - disabled

<details>

Verified ad is not served:

![Image](https://github.com/user-attachments/assets/7ec441cf-3593-4ec2-bd2d-4ec301956ae0)

Verified UI:

![Image](https://github.com/user-attachments/assets/d3427ab0-c013-4c4a-9665-921f6cb3e7fe)|![Image](https://github.com/user-attachments/assets/8d28c4a1-9c68-4974-9067-df0332c9f8c4)
--|--

</details>


#### 30-day history

<details>


</details>
