### ISSUE TITLE
[ads] Eligible ads code health

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#46702]

**Comment by btlechowski** [comment]
Verified with

Brave | 1.81.114 Chromium: 138.0.7204.101 (Official Build) beta (64-bit)
-- | --
Revision | 7299e960857133474b5b22c255832035cb6bd7cf
OS | Linux

### Non-rewards


#### NTT

<details>

Served the ad

```
[6122:6122:0801/220710.114558:VERBOSE1:brave/components/brave_ads/core/internal/serving/new_tab_page_ad_serving.cc:149] Found 1 eligible ads
[6122:6122:0801/220710.114576:VERBOSE1:brave/components/brave_ads/core/internal/serving/new_tab_page_ad_serving.cc:154] Chosen eligible ad with creative instance id ef2ac6fc-7d91-4fef-acdf-f34c1a514443 and a priority of 1
[6122:6122:0801/220710.114675:VERBOSE1:brave/components/brave_ads/core/internal/ad_units/new_tab_page_ad/new_tab_page_ad_handler.cc:144] Served new tab page ad impression:
  placementId: 106dff09-4f92-41aa-853a-28f4ebab7317
  creativeInstanceId: ef2ac6fc-7d91-4fef-acdf-f34c1a514443
  creativeSetId: 46cf9cc5-4932-4440-9aca-96ce04c73aa2
  campaignId: 0c281843-7d8b-40f1-9bb9-91d4e74ff5a4
  advertiserId: 803953a8-56b4-4d4b-942a-fa81357f1427
  segment: untargeted
  companyName: Brave - The image is a 2560x2560 square
  alt: The image is a 2560x2560 square.
  targetUrl: chrome://settings/search
[6122:6122:0801/220710.154296:VERBOSE3:brave/components/brave_ads/core/internal/ad_units/new_tab_page_ad/new_tab_page_ad_handler.cc:151] Served new tab page ad impression with placement id 106dff09-4f92-41aa-853a-28f4ebab7317 and creative instance id ef2ac6fc-7d91-4fef-acdf-f34c1a514443

```


Shown the ad

<img width="1307" height="706" alt="Image" src="https://github.com/user-attachments/assets/72b0f5f6-068a-4a59-bdf7-cece0b47f5f6" />


</details>



### Rewards

#### NTT

<details>

Served the ad

```
[6122:6122:0801/221321.683897:VERBOSE3:brave/components/brave_ads/core/internal/serving/eligible_ads/priority/priority_util.h:23] 5 untargeted ads with a priority of 1 in bucket 1
[6122:6122:0801/221321.684358:VERBOSE1:brave/components/brave_ads/core/internal/serving/eligible_ads/pipelines/new_tab_page_ads/eligible_new_tab_page_ads_v2.cc:276] Predicted ad with creative instance id ef2ac6fc-7d91-4fef-acdf-f34c1a514443 and a priority of 1
[6122:6122:0801/221321.684486:VERBOSE1:brave/components/brave_ads/core/internal/serving/new_tab_page_ad_serving.cc:149] Found 1 eligible ads
[6122:6122:0801/221321.684680:VERBOSE1:brave/components/brave_ads/core/internal/serving/new_tab_page_ad_serving.cc:154] Chosen eligible ad with creative instance id ef2ac6fc-7d91-4fef-acdf-f34c1a514443 and a priority of 1
[6122:6122:0801/221321.684834:VERBOSE1:brave/components/brave_ads/core/internal/ad_units/new_tab_page_ad/new_tab_page_ad_handler.cc:144] Served new tab page ad impression:
  placementId: 2452c008-2063-4947-a9f6-626961188f07
  creativeInstanceId: ef2ac6fc-7d91-4fef-acdf-f34c1a514443
  creativeSetId: 46cf9cc5-4932-4440-9aca-96ce04c73aa2
  campaignId: 0c281843-7d8b-40f1-9bb9-91d4e74ff5a4
  advertiserId: 803953a8-56b4-4d4b-942a-fa81357f1427
  segment: untargeted
  companyName: Brave - The image is a 2560x2560 square
  alt: The image is a 2560x2560 square.
  targetUrl: chrome://settings/search
[6122:6122:0801/221321.715397:VERBOSE3:brave/components/brave_ads/core/internal/ad_units/new_tab_page_ad/new_tab_page_ad_handler.cc:151] Served new tab page ad impression with placement id 2452c008-2063-4947-a9f6-626961188f07 and creative instance id ef2ac6fc-7d91-4fef-acdf-f34c1a514443

```


Shown the ad

<img width="1307" height="706" alt="Image" src="https://github.com/user-attachments/assets/16cfb569-4cf7-4cf5-b014-04a78c1ec810" />


view event
```
[6122:6122:0801/221412.228146:VERBOSE1:brave/components/brave_ads/core/internal/account/utility/redeem_confirmation/non_reward/redeem_non_reward_confirmation.cc:58] Redeem non-reward confirmation
[6122:6122:0801/221412.228240:VERBOSE1:brave/components/brave_ads/core/internal/account/utility/redeem_confirmation/non_reward/redeem_non_reward_confirmation.cc:67] Create non-reward confirmation
[6122:6122:0801/221412.228292:VERBOSE6:brave/components/brave_ads/core/internal/account/utility/redeem_confirmation/non_reward/redeem_non_reward_confirmation.cc:72] URL Request:
  URL: https://anonymous.ads.bravesoftware.com/v4/confirmation/9ef07875-df90-4b20-9c8a-fa021cef4dcf
  Content: {"buildChannel":"beta","catalog":[{"id":"m6yui8Z8QHtK2m0QE1/ckycIqvCQEX02U8Ge+pIfUIU="}],"createdAtTimestamp":"2025-08-01T20:00:00.000Z","creativeInstanceId":"ef2ac6fc-7d91-4fef-acdf-f34c1a514443","platform":"linux","rotatingHash":"DES2HgQIrAmz8FMwVkrjpUzDuYIY5h1gdvyuzIdk3J4=","segment":"untargeted","studies":[],"systemTimestamp":"2025-08-01T20:00:00.000Z","type":"view","versionNumber":"139.0.7258.42"}
  Content Type: application/json
  Method: kPost
[6122:6122:0801/221412.228315:VERBOSE7:brave/components/brave_ads/core/internal/account/utility/redeem_confirmation/non_reward/redeem_non_reward_confirmation.cc:73]   Headers:
    accept: application/json
[6122:6122:0801/221412.965067:VERBOSE6:brave/components/brave_ads/core/internal/account/utility/redeem_confirmation/non_reward/redeem_non_reward_confirmation.cc:86] URL Response:
  URL: https://anonymous.ads.bravesoftware.com/v4/confirmation/9ef07875-df90-4b20-9c8a-fa021cef4dcf
  Response Status Code: 204
  Response: 
[6122:6122:0801/221412.965126:VERBOSE7:brave/components/brave_ads/core/internal/account/utility/redeem_confirmation/non_reward/redeem_non_reward_confirmation.cc:87]   Headers:
    accept-ranges: bytes
    access-control-allow-credentials: true
    content-security-policy: sandbox
    cross-origin-opener-policy: same-origin
    cross-origin-resource-policy: same-origin
    date: Fri, 01 Aug 2025 20:14:21 GMT
    referrer-policy: same-origin
    strict-transport-security: max-age=31536000; includeSubDomains; preload
    vary: Origin
    via: 1.1 varnish
    x-cache: MISS
    x-cache-hits: 0
    x-content-type-options: nosniff
    x-frame-options: DENY
    x-served-by: cache-fra-eddf8230154-FRA
[6122:6122:0801/221412.965162:VERBOSE1:brave/components/brave_ads/core/internal/account/utility/redeem_confirmation/non_reward/redeem_non_reward_confirmation.cc:104] Successfully redeemed non-reward kViewedImpression confirmation for kNewTabPageAd with transaction id 9ef07875-df90-4b20-9c8a-fa021cef4dcf and creative instance id ef2ac6fc-7d91-4fef-acdf-f34c1a514443
[6122:6122:0801/221412.988895:VERBOSE1:brave/components/brave_ads/core/internal/account/confirmations/confirmations.cc:93] Successfully processed kViewedImpression confirmation for kNewTabPageAd with transaction id 9ef07875-df90-4b20-9c8a-fa021cef4dcf and creative instance id ef2ac6fc-7d91-4fef-acdf-f34c1a514443

```



</details>


#### Notification ad

<details>


Served the ad
```
[6122:6122:0801/221009.677682:VERBOSE2:brave/components/brave_ads/core/internal/serving/eligible_ads/pacing/pacing_util.h:28] Pacing delivery for creative instance id 7dc05e12-e186-4507-a61f-9881daec1340 [Roll(0.000100):0.153903]
[6122:6122:0801/221009.677725:VERBOSE2:brave/components/brave_ads/core/internal/serving/eligible_ads/pacing/pacing_util.h:28] Pacing delivery for creative instance id 7dc05e12-e186-4507-a61f-9881daec1340 [Roll(0.000100):0.526665]
[6122:6122:0801/221009.677760:VERBOSE3:brave/components/brave_ads/core/internal/serving/eligible_ads/priority/priority_util.h:23] 12 untargeted ads with a priority of 1 in bucket 1
[6122:6122:0801/221009.677781:VERBOSE1:brave/components/brave_ads/core/internal/serving/eligible_ads/pipelines/notification_ads/eligible_notification_ads_v2.cc:169] Predicted ad with creative instance id c1e56640-0a4b-4196-ad44-7221ca29f4cd and a priority of 1
[6122:6122:0801/221009.677808:VERBOSE1:brave/components/brave_ads/core/internal/serving/notification_ad_serving.cc:177] Found 1 eligible ads
[6122:6122:0801/221009.677825:VERBOSE1:brave/components/brave_ads/core/internal/serving/notification_ad_serving.cc:182] Chosen eligible ad with creative instance id c1e56640-0a4b-4196-ad44-7221ca29f4cd and a priority of 1
[6122:6122:0801/221009.677851:VERBOSE1:brave/components/brave_ads/core/internal/ad_units/notification_ad/notification_ad_handler.cc:172] Served notification ad impression:
  placementId: bfa4aa27-74ea-461b-86e0-a50642b77f96
  creativeInstanceId: c1e56640-0a4b-4196-ad44-7221ca29f4cd
  creativeSetId: 45ea5952-37ca-41f0-88c2-4b546b0e6f4b
  campaignId: 1c1ac828-db13-49bb-9128-090132044b7f
  advertiserId: ecbcc833-8b1d-4867-98f7-ad2341396ce8
  segment: untargeted
  title: Ad3
  body: Ad3
  targetUrl: https://brave.com/

```

Shown the ad

<img width="1307" height="706" alt="Image" src="https://github.com/user-attachments/assets/080a19ff-0820-4f63-9911-4c62069e6325" />

view event
```
[6122:6122:0801/221009.721622:VERBOSE3:brave/components/brave_ads/core/internal/ad_units/notification_ad/notification_ad_handler.cc:183] Served notification ad impression with placement id bfa4aa27-74ea-461b-86e0-a50642b77f96 and creative instance id c1e56640-0a4b-4196-ad44-7221ca29f4cd
[6122:6122:0801/221009.748627:VERBOSE3:brave/components/brave_ads/core/internal/ad_units/notification_ad/notification_ad_handler.cc:190] Viewed notification ad impression with placement id bfa4aa27-74ea-461b-86e0-a50642b77f96 and creative instance id c1e56640-0a4b-4196-ad44-7221ca29f4cd
[6122:6122:0801/221009.768812:VERBOSE3:brave/components/brave_ads/core/internal/history/ad_history_database_table_util.cc:33] Successfully saved ad history
[6122:6122:0801/221009.789908:VERBOSE3:brave/components/brave_ads/core/internal/account/account.cc:166] Successfully processed deposit for kNotificationAd with creative instance id c1e56640-0a4b-4196-ad44-7221ca29f4cd and kViewedImpression valued at 0
[6122:6122:0801/221009.790004:VERBOSE1:brave/components/brave_ads/core/internal/account/confirmations/confirmations.cc:40] Confirming kViewedImpression for kNotificationAd with transaction id 11d3df59-bb9d-4ec9-aee9-93fcd41d5762 and creative instance id c1e56640-0a4b-4196-ad44-7221ca29f4cd
[6122:6122:0801/221009.817748:VERBOSE1:brave/components/brave_ads/core/internal/account/confirmations/confirmations.cc:73] Successfully added kViewedImpression confirmation for kNotificationAd with transaction id 11d3df59-bb9d-4ec9-aee9-93fcd41d5762 and creative instance id c1e56640-0a4b-4196-ad44-7221ca29f4cd to the queue
[6122:6122:0801/221009.820374:VERBOSE1:brave/components/brave_ads/core/internal/account/confirmations/confirmations.cc:84] Process kViewedImpression confirmation for kNotificationAd with transaction id 11d3df59-bb9d-4ec9-aee9-93fcd41d5762 and creative instance id c1e56640-0a4b-4196-ad44-7221ca29f4cd in 0 hours, 0 minutes, 5 seconds at 22:10:14.817
[6122:6122:0801/221011.958083:INFO:CONSOLE:124] "TypeError: Cannot read properties of null (reading 'sendMessage')", source: https://www.gstatic.com/og/_/js/k=og.asy.en_US.H3gxb8WkWCg.2019.O/rt=j/m=_ac,_awd,ada,lldp,qads/exm=/d=1/ed=1/rs=AA2YrTshnTjrUywXqYjDJG1BQQtKjQgFdw (124)
[6122:6122:0801/221014.820736:VERBOSE1:brave/components/brave_ads/core/internal/account/utility/redeem_confirmation/non_reward/redeem_non_reward_confirmation.cc:58] Redeem non-reward confirmation
[6122:6122:0801/221014.821057:VERBOSE1:brave/components/brave_ads/core/internal/account/utility/redeem_confirmation/non_reward/redeem_non_reward_confirmation.cc:67] Create non-reward confirmation
[6122:6122:0801/221014.821111:VERBOSE6:brave/components/brave_ads/core/internal/account/utility/redeem_confirmation/non_reward/redeem_non_reward_confirmation.cc:72] URL Request:
  URL: https://anonymous.ads.bravesoftware.com/v4/confirmation/11d3df59-bb9d-4ec9-aee9-93fcd41d5762
  Content: {"buildChannel":"beta","catalog":[{"id":"m6yui8Z8QHtK2m0QE1/ckycIqvCQEX02U8Ge+pIfUIU="}],"createdAtTimestamp":"2025-08-01T20:00:00.000Z","creativeInstanceId":"c1e56640-0a4b-4196-ad44-7221ca29f4cd","firstTime":true,"platform":"linux","rotatingHash":"mSeT/ePzdLYivdHVaXcDpvfnvLXRoBQCESURWB98cXs=","segment":"untargeted","studies":[],"systemTimestamp":"2025-08-01T20:00:00.000Z","type":"view","versionNumber":"139.0.7258.42"}
  Content Type: application/json
  Method: kPost
[6122:6122:0801/221014.821134:VERBOSE7:brave/components/brave_ads/core/internal/account/utility/redeem_confirmation/non_reward/redeem_non_reward_confirmation.cc:73]   Headers:
    accept: application/json
[6122:6122:0801/221016.599464:VERBOSE6:brave/components/brave_ads/core/internal/account/utility/redeem_confirmation/non_reward/redeem_non_reward_confirmation.cc:86] URL Response:
  URL: https://anonymous.ads.bravesoftware.com/v4/confirmation/11d3df59-bb9d-4ec9-aee9-93fcd41d5762
  Response Status Code: 204
  Response: 
[6122:6122:0801/221016.599619:VERBOSE7:brave/components/brave_ads/core/internal/account/utility/redeem_confirmation/non_reward/redeem_non_reward_confirmation.cc:87]   Headers:
    accept-ranges: bytes
    access-control-allow-credentials: true
    content-security-policy: sandbox
    cross-origin-opener-policy: same-origin
    cross-origin-resource-policy: same-origin
    date: Fri, 01 Aug 2025 20:10:24 GMT
    referrer-policy: same-origin
    strict-transport-security: max-age=31536000; includeSubDomains; preload
    vary: Origin
    via: 1.1 varnish
    x-cache: MISS
    x-cache-hits: 0
    x-content-type-options: nosniff
    x-frame-options: DENY
    x-served-by: cache-fra-eddf8230154-FRA
[6122:6122:0801/221016.599669:VERBOSE1:brave/components/brave_ads/core/internal/account/utility/redeem_confirmation/non_reward/redeem_non_reward_confirmation.cc:104] Successfully redeemed non-reward kViewedImpression confirmation for kNotificationAd with transaction id 11d3df59-bb9d-4ec9-aee9-93fcd41d5762 and creative instance id c1e56640-0a4b-4196-ad44-7221ca29f4cd
[6122:6122:0801/221016.635505:VERBOSE1:brave/components/brave_ads/core/internal/account/confirmations/confirmations.cc:93] Successfully processed kViewedImpression confirmation for kNotificationAd with transaction id 11d3df59-bb9d-4ec9-aee9-93fcd41d5762 and creative instance id c1e56640-0a4b-4196-ad44-7221ca29f4cd

```

</details>
